name: build and test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Here, you can use the secret in your commands or scripts
      - name: Use Secret in Workflow
        run: echo "The API key is ${{ secrets.TRANSLATOR_API_KEY }}"
      
      - name: Find and Replace the API Key
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "This is the Azure Translator ApiKey"
          replace: ${{ secrets.TRANSLATOR_API_KEY }}
          include: "**appsettings.json"

      # Install .NET Core SDK
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run Tests from solution
        run: dotnet test

      - name: Install .NET WASM build tools workload
        run: dotnet workload install wasm-tools

      - name: Publish Blazor Project to the release folder 
        run: dotnet publish ./LanguageFileTranslatorApp/LanguageFileTranslatorApp.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/Web/wwwroot
          
